spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://yebali.iptime.org:5432/search
    username: postgres
    password: c1d0962c505d
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
