spring:
  application:
    name: search
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/search
    username: postgres
    password: testpassword
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

external-api:
  naver:
    url: https://openapi.naver.com/v1/search
    client-id: ${NAVER_CLIENT_ID:xzHScQ0zpE1rAGoAs9mm}
    client-secret: ${NAVER_CLIENT_SECRET:Z2_plh1IL2}
