name: Publish to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Publish Docker Image To ECR
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up JDK17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Run Tests
      run: ./gradlew clean test

    - name: Build and Publish
      run: ./gradlew clean jib
